
from PyQt5 import QtCore, QtGui, QtWidgets


class records(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1484, 864)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(8, 39, 79)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.TimeSet = QtWidgets.QPushButton(self.centralwidget)
        self.TimeSet.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.TimeSet.setFont(font)
        self.TimeSet.setStyleSheet("background-color: white;")
        self.TimeSet.setObjectName("TimeSet")
        self.TimeSet.clicked.connect(self.open_time_set)
        self.gridLayout.addWidget(self.TimeSet, 0, 6, 1, 1)
        self.Search = QtWidgets.QLineEdit(self.centralwidget)
        self.Search.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.Search.setFont(font)
        self.Search.setStyleSheet("background-color: white;")
        self.Search.setText("")
        self.Search.setObjectName("Search")
        self.gridLayout.addWidget(self.Search, 0, 1, 1, 1)
        self.Timeout = QtWidgets.QPushButton(self.centralwidget)
        self.Timeout.setMinimumSize(QtCore.QSize(70, 0))
        self.Timeout.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.Timeout.setFont(font)
        self.Timeout.setStyleSheet("background-color: white;")
        self.Timeout.setObjectName("Timeout")
        self.gridLayout.addWidget(self.Timeout, 0, 5, 1, 1)
        self.Timein = QtWidgets.QPushButton(self.centralwidget)
        self.Timein.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.Timein.setFont(font)
        self.Timein.setStyleSheet("background-color: white;")
        self.Timein.setObjectName("Timein")
        self.gridLayout.addWidget(self.Timein, 0, 3, 1, 1)
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Back.setFont(font)
        self.Back.setStyleSheet("background-color: white;")
        self.Back.setObjectName("Back")
        self.Back.clicked.connect(self.go_back)
        self.gridLayout.addWidget(self.Back, 0, 9, 1, 1)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Save.setFont(font)
        self.Save.setStyleSheet("background-color: white;")
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 0, 7, 1, 1)
        self.Records = QtWidgets.QPushButton(self.centralwidget)
        self.Records.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.Records.setFont(font)
        self.Records.setStyleSheet("background-color: white;")
        self.Records.setObjectName("Records")
        self.gridLayout.addWidget(self.Records, 0, 8, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.EmployeeTable = QtWidgets.QTableWidget(self.centralwidget)
        self.EmployeeTable.setMinimumSize(QtCore.QSize(1350, 0))
        self.EmployeeTable.setMaximumSize(QtCore.QSize(980, 700))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.EmployeeTable.setFont(font)
        self.EmployeeTable.setStyleSheet("background-color: white;")
        self.EmployeeTable.setWordWrap(True)
        self.EmployeeTable.setRowCount(1)
        self.EmployeeTable.setObjectName("EmployeeTable")
        self.EmployeeTable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        item.setFont(font)
        self.EmployeeTable.setHorizontalHeaderItem(5, item)
        self.EmployeeTable.horizontalHeader().setCascadingSectionResizes(False)
        self.EmployeeTable.horizontalHeader().setDefaultSectionSize(220)
        self.EmployeeTable.horizontalHeader().setMinimumSectionSize(220)
        self.EmployeeTable.horizontalHeader().setSortIndicatorShown(False)
        self.EmployeeTable.horizontalHeader().setStretchLastSection(True)
        self.EmployeeTable.verticalHeader().setVisible(True)
        self.EmployeeTable.verticalHeader().setCascadingSectionResizes(False)
        self.EmployeeTable.verticalHeader().setDefaultSectionSize(40)
        self.EmployeeTable.verticalHeader().setMinimumSectionSize(0)
        self.EmployeeTable.verticalHeader().setSortIndicatorShown(True)
        self.EmployeeTable.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.EmployeeTable)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1484, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TimeSet.setText(_translate("MainWindow", "Time Set"))
        self.Search.setPlaceholderText(_translate("MainWindow", "Employee Name"))
        self.Timeout.setText(_translate("MainWindow", "Time Out"))
        self.Timein.setText(_translate("MainWindow", "Time In"))
        self.Back.setText(_translate("MainWindow", "Back"))
        self.Save.setText(_translate("MainWindow", "Save"))
        self.Records.setText(_translate("MainWindow", "Records"))
        item = self.EmployeeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.EmployeeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee"))
        item = self.EmployeeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time in"))
        item = self.EmployeeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.EmployeeTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time out"))
        item = self.EmployeeTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date"))

    def go_back(self):
        """Function to return to the Admin Panel."""
        from src.frontend.admin_panel import admin_panel
        self.window = QtWidgets.QMainWindow()
        self.ui = admin_panel()
        self.ui.setupUi(self.window)
        self.window.show()
        QtWidgets.QApplication.instance().activeWindow().close()  

    def open_time_set(self):
        """Function to open time set ui"""
        from src.frontend.time_set import SetWorkTimePanel
        self.ui = SetWorkTimePanel() 
        self.ui.show() #show window

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = records()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
